feat: menu hamburguesa de dashboard
igrowker/i003-cerem-front pull request #42
Opened 2024-09-16 01:02 UTC by leandromortarini2

2024-09-16 13:07 UTC, fran-albert commented on src/components/Dashboard/index.tsx
1. Hay que reemplazar el Button de Dashboard por un componente reutlizable. 
2. Que ocupe el ancho de la pantalla cuando el menú este abierto
![image](https://github.com/user-attachments/assets/cdc576d0-5ccd-49d3-bbd3-be576798cb89)

2024-09-16 13:09 UTC, fran-albert requested changes
Crear un componente reutilizable para el burguer menu donde se pueda insertar en los distintos components (dashboard, tareas, calendar, clients, etc)

2024-09-17 01:35 UTC, leandromortarini2 commented on src/components/Dashboard/index.tsx
Listo Los cambios! El burguer ocupa el 100% en mobile pero no en tablet quedaba feo

2024-09-17 12:43 UTC, fran-albert approved these changes

2024-09-17 12:43 UTC, merged